### ISSUE TITLE
Jetbrains 2020.3 I can't afford it ,

### ISSUE THREAD

**Issue by yinxiulong** [brpaz/ulauncher-jetbrains#29]
recentProjects.xml No list
```
  <option name="recentPaths">
      <list>

````

**Comment by steamer-vparker** [comment]
Yeah I can't get the file to populate either.

**Comment by PaulVanSchayck** [comment]
Seems like we need to parse the main list now, and sort by the `projectOpenTimestamp` elements ourselves.
