### ISSUE TITLE
Nothing happens if opening a recent project

### ISSUE THREAD

**Issue by tobika** [brpaz/ulauncher-jetbrains#3]
Hi,
I'm not sure if this a bug with this plugin or ulauncher or a mis-configuration on my side.

When I try to open a recent project in WebStorm nothing happens. I have the following in my log if I start ulauncher with `ulauncher -v`

`/tmp/ulauncher_RunScript_2h3F9b: 1: /tmp/ulauncher_RunScript_2h3F9b: /home/tobika/.WebStorm2019.1/config/options/recentProjectDirectories.xml: Permission denied
`

In my terminal I can start WebStorm with the `webstorm` command.

**Comment by brpaz** [comment]
it seems Ulauncher cant read your recentProjectDIrectories file. Please make sure the path is correctly configured in the plugin settings and the file readable by your user.

**Comment by elue** [comment]
The problem still exists, the directories are listed down and there is no action on it.

**Comment by pwnyprod** [comment]
Jetbrains have 2 different types of xml files but the parser only interprets one. Needs to be refactored. (if i find time i will do this if you don't mind)

**Comment by pwnyprod** [comment]
EDIT: Old versions of Jetbrain tools had another xml file and use another type of tree in it. Update your version maybe.

**Comment by tobika** [comment]
For me the problems seems to be solved. Thanks a lot :)
